# Generated by Django 4.2.1 on 2023-05-30 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motorInferencia', '0002_alter_article_title_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(default='null', upload_to=''),
        ),
    ]
